version: '3.9'

services:
  api:
    image: 'myclient:latest'
    build:
      context: .
    ports:
      - "9595:8080"
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=MobileApp
      - MYSQL_ROOT_PASSWORD=E7LEXCJ6
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
      driver: local